vim.pack.add({
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter', version = 'main' },
  'https://github.com/mason-org/mason.nvim',
  'https://github.com/mason-org/mason-lspconfig.nvim',
})

require('nvim-treesitter').install({
  'bash',
  'c',
  'comment',
  'css',
  'diff',
  'dockerfile',
  'editorconfig',
  'git_config',
  'gitcommit',
  'gitignore',
  'glimmer',
  'html',
  'htmldjango',
  'http',
  'ini',
  'javascript',
  'jinja',
  'jsdoc',
  'json',
  'json5',
  'lua',
  'make',
  'markdown',
  'markdown_inline',
  'muttrc',
  'php',
  'python',
  'query',
  'regex',
  'ruby',
  'scss',
  'sql',
  'ssh_config',
  'toml',
  'tsx',
  'twig',
  'typescript',
  'vim',
  'vimdoc',
  'vue',
  'xml',
  'yaml',
  'zsh',
})

require('nvim-treesitter.config').setup({
  highlight = { enable = true },
  incremental_selection = { enable = true },
  indent = { enable = true },
})

require('mason').setup()
require('mason-lspconfig').setup({
  ensure_installed = {
    'ast_grep',
    'bashls',
    'css_variables',
    'cssls',
    'cssmodules_ls',
    'emmet_language_server',
    'eslint',
    'html',
    'jsonls',
    'lua_ls',
    'marksman',
    'phpactor',
    'stylelint_lsp',
    'tailwindcss',
    'vtsls',
    'yamlls',
  },
})
