# Minor modifications to terminal prompt
command_timeout = 5_000

[cmd_duration]
min_time = 5_000

[directory]
truncation_length = 6

[custom.tttimetracker]
command = "~/Dotfiles/other/tt-time-tracker.status.zsh" # shows output of command
when = ""
symbol = ""
style = "bold blue"
format = "[$symbol($output)]($style) "
