# Minor modifications to terminal prompt

[cmd_duration]
min_time = 5_000

[directory]
truncation_length = 6

[custom.bartib]
command = "~/Dotfiles/other/bartib.status.zsh" # shows output of command
when = ""
symbol = ""
style = "bold blue"
format = "[$symbol($output)]($style)"
