[misc]
assume_yes = true
cleanup = true
disable = ["pnpm", "composer"]
no_retry = true
pre_sudo = true
run_in_tmux = false
set_title = false
skip_notify = true

[brew]
greedy_cask = true
autoremove = true
