kitty_mod ctrl+cmd

map cmd+t new_tab_with_cwd
map cmd+n new_os_window_with_cwd
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map kitty_mod+/ launch --cwd=current
map kitty_mod+- launch --cwd=current
map kitty_mod+, set_tab_title
map kitty_mod+. set_window_title
map kitty_mod+z toggle_layout stack
map kitty_mod+h move_window left
map kitty_mod+r resize_window reset
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab

map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

map kitty_mod+g goto_session ~/.config/kitty/sessions
