# fonts and text
font_family Maple Mono NF
font_features MapleMono-NF-Regular +calt +zero +cv01
font_size 15
modify_font cell_height 110%
cursor_blink_interval 0
cursor_shape block
cursor_shape_unfocused hollow

# minimal ui and interface settings
confirm_os_window_close 0
enabled_layouts tall,stack
hide_window_decorations yes
inactive_text_alpha 0.5
remember_window_size yes
tab_bar_edge bottom
tab_bar_min_tabs 1
tab_bar_style separator
tab_separator ' '
tab_title_template  '  {index} {title}  '
tab_bar_filter session:~ or session:^$

# system integration and settings
allow_remote_control yes
copy_on_select yes
detect_urls yes
listen_on unix:/tmp/mykitty
macos_dock_badge_on_bell yes
macos_option_as_alt left
macos_quit_when_last_window_closed yes
repaint_delay 0
scrollback_lines 50000
shell /opt/homebrew/bin/zsh
shell_integration no-cursor

# sessions, theme and keybindings
include current-theme.conf
include keybindings.conf
startup_session ~/.config/kitty/sessions/default.kitty-session
