alias -- -='$EDITOR $(fzf)'
alias ...='cd ../..'
alias ..='cd ..'
alias O="cd ~ && mbsync -a && mu index"
alias g="git"
alias gd="git diff"
alias gf="git-flow"
alias ggpl='git pull origin $(current_branch)'
alias ggpnp='git pull origin $(current_branch) && git push origin $(current_branch)'
alias ggps='git push origin $(current_branch)'
alias gmo='$EDITOR $(git ls-files -m)'
alias gs="git status"
alias lg='lazygit'
alias m='neomutt'
alias mutt='neomutt'
alias nb="npm run build"
alias np="npm run lint && npm run production"
alias nre='n engine && rm -f package-lock.json && rm -rf node_modules && npm install'
alias ns="npm start"
alias out="node ~/Dotfiles/other/out/main.js"
alias q='exit'
alias sudo='sudo '
alias t='tmux -u -2'
alias ta='tmux -u attach'
alias to='tiptop --net en0'
alias upall='n lts && topgrade && npm-check -gu && vimup && brew cleanup && brew autoremove'
alias v=$EDITOR
alias vd='$EDITOR -d'
alias vdiff='$EDITOR -d'
alias vi=$EDITOR
alias vim=$EDITOR
alias vimdiff='$EDITOR -d'
alias vimup='nvim +TSUpdate'
alias yb='yarn build'
alias yp='yarn lint && yarn production'
alias yre='n engine > /dev/null && rm -f yarn.lock && rm -rf node_modules && yarn'
alias ys='yarn start'
