# zinit
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# plugins
zi load zsh-users/zsh-autosuggestions
zi load zsh-users/zsh-completions
zi load zdharma-continuum/fast-syntax-highlighting
zi load starship/starship
zi snippet PZTM::history
zi snippet PZTM::completion

# Fixes for unicode
setopt COMBINING_CHARS

# additional gruvbox colors
source ~/.local/share/nvim/lazy/gruvbox-baby/extras/bash/MEDIUM.bash
source ~/.local/share/nvim/lazy/gruvbox-baby/extras/fzf/fzf.theme

# exports, functions and aliases
source ~/dotfiles/zsh/exports.zsh
source ~/dotfiles/zsh/aliases.zsh
source ~/dotfiles/zsh/functions.zsh

# easy vim/terminal switch
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# other tools init, pyenv + rbenv are sandboxd
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(starship init zsh)"
eval "$(jump shell)"
eval "$(rbenv init - --no-rehash)"
eval "$(pyenv init --path --no-rehash)"

# chat-gpt, hooray
source ~/OPENAI_API_KEY.sh

